#!/usr/bin/env bash
# zDSH-go self-contained installer (Linux/macOS/WSL/Git Bash).
# Installs dependencies, builds the CLI, and keeps every data directory inside
# <repo>/data so the whole installation can be removed with scripts/uninstall.sh.
# Usage: ./scripts/install.sh

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

echo 'zDSH-go installer'
echo "Repository root: $ROOT"
echo ''

# Required Node.js range: ^22.19.0 || >=24
node_ok() {
  command -v node >/dev/null 2>&1 || return 1
  local version
  version="$(node --version 2>/dev/null | sed 's/^v//')" || return 1
  local major minor patch
  major="${version%%.*}"
  local rest="${version#*.}"
  minor="${rest%%.*}"
  patch="${rest#*.}"
  case "$major" in
    ''|*[!0-9]*) return 1 ;;
  esac
  case "$minor" in ''|*[!0-9]*) minor=0 ;; esac
  case "$patch" in ''|*[!0-9]*) patch=0 ;; esac
  if [ "$major" -ge 24 ]; then return 0; fi
  if [ "$major" -eq 22 ] && [ "$minor" -ge 19 ]; then return 0; fi
  return 1
}

if ! node_ok; then
  echo '[X] Node.js is missing or its version is unsupported.'
  echo '    Required: Node.js ^22.19.0 || >=24 (23.x is not supported).'
  echo '    Install Node.js 24 LTS from https://nodejs.org/ (or via nvm), then re-run ./scripts/install.sh'
  exit 1
fi
echo "[OK] Node.js $(node --version)"

if ! command -v pnpm >/dev/null 2>&1; then
  echo '[X] pnpm was not found on PATH.'
  echo '    Enable it with: corepack enable pnpm'
  echo '    (or install it with: npm install -g pnpm), then re-run this script.'
  exit 1
fi
echo "[OK] pnpm $(pnpm --version)"

export CI=true

cd -- "$ROOT"
echo '[1/4] pnpm install --frozen-lockfile'
pnpm install --frozen-lockfile

echo '[2/4] pnpm run build'
pnpm run build

echo '[3/4] Creating data directory'
mkdir -p -- "$ROOT/data"

echo '[4/4] Writing env.sh / env.ps1'
# Node consumes DSH_HOME/DSH_AGENTS_HOME as raw values, so on Windows (Git Bash)
# they must be drive-letter paths, not MSYS /g/... paths. cygpath -m converts
# them (G:/dir form, accepted by Node, PowerShell and bash alike); on
# Linux/macOS cygpath is absent and ROOT is already correct.
NATIVE_ROOT="$ROOT"
if command -v cygpath >/dev/null 2>&1; then
  NATIVE_ROOT="$(cygpath -m -- "$ROOT")"
fi

cat > "$ROOT/env.sh" <<EOF
# Generated by zDSH-go scripts/install.sh. Load with:  source ./env.sh
export DSH_HOME="$NATIVE_ROOT/data"
export DSH_BRANCH_HOME="$NATIVE_ROOT/data/zdsh"
export DSH_AGENTS_HOME="$NATIVE_ROOT/data/agents"
dsh() { node "$NATIVE_ROOT/apps/cli/lib/bin.js" "\$@"; }
EOF

# env.ps1 gets a UTF-8 BOM so Windows PowerShell 5.1 dot-sourcing reads
# non-ASCII paths correctly (mirrors scripts/install.ps1); env.sh must stay
# BOM-free or bash rejects it.
printf '\xEF\xBB\xBF' > "$ROOT/env.ps1"
cat >> "$ROOT/env.ps1" <<EOF
# Generated by zDSH-go scripts/install.sh. Load with:  . .\env.ps1
\$env:DSH_HOME = "$NATIVE_ROOT/data"
\$env:DSH_BRANCH_HOME = "$NATIVE_ROOT/data/zdsh"
\$env:DSH_AGENTS_HOME = "$NATIVE_ROOT/data/agents"
function dsh { & node "$NATIVE_ROOT/apps/cli/lib/bin.js" @args }
EOF

echo ''
echo 'zDSH-go installed successfully (self-contained).'
echo "  Data home (DSH_HOME):                  $ROOT/data"
echo "  zDSH-go branch home (DSH_BRANCH_HOME): $ROOT/data/zdsh"
echo "  Official skills (DSH_AGENTS_HOME): $ROOT/data/agents"
echo ''
echo 'Load the environment, then run the CLI:'
echo '  source ./env.sh'
echo '  dsh web'
echo ''
echo 'Uninstall later with:'
echo '  ./scripts/uninstall.sh               # clean all repo artifacts (node_modules, build output, data/, env files)'
echo '  ./scripts/uninstall.sh --purge       # also delete the whole repository directory'
echo '  ./scripts/uninstall.sh --clean-legacy # also remove the zDSH-go home (~/.dsh-zdsh-go) and legacy plugin homes (main-tree ~/.dsh-zdsh untouched)'
