# zDSH-go self-contained installer (Windows PowerShell 5.1+).
# Installs dependencies, builds the CLI, and keeps every data directory inside
# <repo>\data so the whole installation can be removed with uninstall.cmd.
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File scripts\install.ps1

$ErrorActionPreference = 'Continue'

$ROOT = Split-Path -Parent $PSScriptRoot
if (-not $ROOT) { $ROOT = (Get-Location).Path }

Write-Host 'zDSH-go installer'
Write-Host "Repository root: $ROOT"
Write-Host ''

# Required Node.js range: ^22.19.0 || >=24
function Test-NodeVersion {
    $previousEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $versionOutput = & node --version 2>$null
    }
    catch {
        $ErrorActionPreference = $previousEap
        return $false
    }
    $ErrorActionPreference = $previousEap
    if ($LASTEXITCODE -ne 0 -or -not $versionOutput) { return $false }
    $version = ([string]($versionOutput | Select-Object -First 1)).Trim() -replace '^v', ''
    $segments = $version.Split('.')
    if ($segments.Count -lt 3) { return $false }
    $major = 0
    $minor = 0
    $patch = 0
    if (-not [int]::TryParse($segments[0], [ref]$major)) { return $false }
    if (-not [int]::TryParse($segments[1], [ref]$minor)) { return $false }
    if (-not [int]::TryParse($segments[2], [ref]$patch)) { return $false }
    if ($major -ge 24) { return $true }
    if ($major -eq 22 -and ($minor -gt 19 -or ($minor -eq 19 -and $patch -ge 0))) { return $true }
    return $false
}

if (-not (Get-Command node -ErrorAction SilentlyContinue) -or -not (Test-NodeVersion)) {
    Write-Host '[X] Node.js is missing or its version is unsupported.' -ForegroundColor Red
    Write-Host '    Required: Node.js ^22.19.0 || >=24 (23.x is not supported).'
    Write-Host '    Install Node.js 24 LTS from https://nodejs.org/ (or via nvm/windows-nvm),'
    Write-Host '    then re-run: powershell -NoProfile -ExecutionPolicy Bypass -File scripts\install.ps1'
    exit 1
}
Write-Host "[OK] Node.js $(& node --version)"

if (-not (Get-Command pnpm -ErrorAction SilentlyContinue)) {
    Write-Host '[X] pnpm was not found on PATH.' -ForegroundColor Red
    Write-Host '    Enable it with: corepack enable pnpm'
    Write-Host '    (or install it with: npm install -g pnpm), then re-run this script.'
    exit 1
}
Write-Host "[OK] pnpm $(& pnpm --version)"

$env:CI = 'true'

Push-Location $ROOT
try {
    Write-Host '[1/4] pnpm install --frozen-lockfile'
    & pnpm install --frozen-lockfile
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    Write-Host '[2/4] pnpm run build'
    & pnpm run build
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    # dsh-guard integrity check of the web profile (read-only). Non-blocking by
    # design (PLAN D5): a fresh install has no profile yet, so any non-zero
    # exit here is a warning only; the report is the guard's console output.
    Write-Host '[2b/4] dsh-guard check (profile web, non-blocking)'
    & node (Join-Path $ROOT 'packages\plugins\dsh-guard\dsh-guard.mjs') check --profile web
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[WARN] dsh-guard check failed (exit code $LASTEXITCODE); continuing (non-blocking)." -ForegroundColor Yellow
    }
}
finally {
    Pop-Location
}

Write-Host '[3/4] Creating data directory'
$dataDir = Join-Path $ROOT 'data'
New-Item -ItemType Directory -Path $dataDir -Force | Out-Null

Write-Host '[4/4] Writing env.ps1 / env.sh'

$envPs1Content = @'
# Generated by zDSH-go scripts/install.ps1. Load with:  . .\env.ps1
$env:DSH_HOME = "__DSH_HOME__"
$env:DSH_BRANCH_HOME = "__DSH_BRANCH_HOME__"
$env:DSH_AGENTS_HOME = "__DSH_AGENTS_HOME__"
function dsh { & node "__CLI_JS__" @args }
'@
$envPs1Content = $envPs1Content.Replace('__DSH_HOME__', (Join-Path $ROOT 'data'))
$envPs1Content = $envPs1Content.Replace('__DSH_BRANCH_HOME__', (Join-Path $ROOT 'data\zdsh'))
$envPs1Content = $envPs1Content.Replace('__DSH_AGENTS_HOME__', (Join-Path $ROOT 'data\agents'))
$envPs1Content = $envPs1Content.Replace('__CLI_JS__', (Join-Path $ROOT 'apps\cli\lib\bin.js'))

$envShContent = @'
# Generated by zDSH-go scripts/install.ps1. Load with:  source ./env.sh
export DSH_HOME="__DSH_HOME__"
export DSH_BRANCH_HOME="__DSH_BRANCH_HOME__"
export DSH_AGENTS_HOME="__DSH_AGENTS_HOME__"
dsh() { node "__CLI_JS__" "$@"; }
'@
$envShContent = $envShContent.Replace('__DSH_HOME__', ($ROOT.Replace('\', '/') + '/data'))
$envShContent = $envShContent.Replace('__DSH_BRANCH_HOME__', ($ROOT.Replace('\', '/') + '/data/zdsh'))
$envShContent = $envShContent.Replace('__DSH_AGENTS_HOME__', ($ROOT.Replace('\', '/') + '/data/agents'))
$envShContent = $envShContent.Replace('__CLI_JS__', ($ROOT.Replace('\', '/') + '/apps/cli/lib/bin.js'))

# env.ps1 gets a UTF-8 BOM so Windows PowerShell 5.1 dot-sourcing reads non-ASCII
# paths correctly; env.sh must stay BOM-free or bash rejects it. Both get a
# trailing newline (here-strings exclude the terminating one).
[IO.File]::WriteAllText((Join-Path $ROOT 'env.ps1'), ($envPs1Content + "`r`n"), (New-Object System.Text.UTF8Encoding($true)))
[IO.File]::WriteAllText((Join-Path $ROOT 'env.sh'), ($envShContent + "`n"), (New-Object System.Text.UTF8Encoding($false)))

Write-Host ''
Write-Host 'zDSH-go installed successfully (self-contained).'
Write-Host "  Data home (DSH_HOME):                  $dataDir"
Write-Host "  zDSH-go branch home (DSH_BRANCH_HOME): $(Join-Path $dataDir 'zdsh')"
Write-Host "  Official skills (DSH_AGENTS_HOME): $(Join-Path $dataDir 'agents')"
Write-Host ''
Write-Host 'Load the environment, then run the CLI:'
Write-Host '  . .\env.ps1'
Write-Host '  dsh web'
Write-Host ''
Write-Host 'Uninstall later with:'
Write-Host '  .\uninstall.cmd               # clean all repo artifacts (node_modules, build output, data\, env files)'
Write-Host '  .\uninstall.cmd -Purge        # also delete the whole repository directory'
Write-Host '  .\uninstall.cmd -CleanLegacy  # also remove the zDSH-go home (~/.dsh-zdsh-go) and legacy plugin homes (main-tree ~/.dsh-zdsh untouched)'
